id: P0788F8B8
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA17319
  instance_id: http://purl.bdrc.io/resource/IE17319
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - བཀའ་ཐང་སྡེ་ལྔ།（མི་རིགས་དཔེ་སྐྲུན་ཁང་།）
  alt_title:
    zh-latn-wadegile:
    - wu pu i chiao
    en-x-mixed:
    - Bkaʼ thaṅ sde lṅa :Gu ru U-rgyan-gliṅ-pas Yar-kluṅs śel gyi brag phug nas bton
      pa.
  author: http://purl.bdrc.io/resource/P4943
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    1c36f6393d4f405eb0880802632200f8:
      title: པོད ༡་བཀའ་ཐང་སྡེ་ལྔ།（མི་རིགས་དཔེ་སྐྲུན་ཁང་།）
      volume_number: 1
      base_file: UT17319_4268_0000.txt
      reference: http://purl.bdrc.io/resource/VLA339C490DB518B0B
      image_group: '4268'
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W17319
  - http://purl.bdrc.io/resource/MW17319
  ocr_software: Namsel
created_at: '2021-12-22T10:23:43.182732'
last_modified_at: '2021-12-22T10:23:43.182739'
